// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8uolfyvhPLZz82SGmnPFtiNKSNSF6UII',
    appId: '1:837466394012:web:f4ead5207009d7d4068c59',
    messagingSenderId: '837466394012',
    projectId: 'suc-forum',
    authDomain: 'suc-forum.firebaseapp.com',
    storageBucket: 'suc-forum.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu99yBtpecN7vw7yOGdLa-CmhHHU41o1s',
    appId: '1:837466394012:android:f671ea39bb03bc29068c59',
    messagingSenderId: '837466394012',
    projectId: 'suc-forum',
    storageBucket: 'suc-forum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhCJM03GYzq9-8xnZUH6THiInoT88El4',
    appId: '1:837466394012:ios:7b938adf5ea1a47f068c59',
    messagingSenderId: '837466394012',
    projectId: 'suc-forum',
    storageBucket: 'suc-forum.firebasestorage.app',
    iosBundleId: 'com.example.sucForum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQhCJM03GYzq9-8xnZUH6THiInoT88El4',
    appId: '1:837466394012:ios:7b938adf5ea1a47f068c59',
    messagingSenderId: '837466394012',
    projectId: 'suc-forum',
    storageBucket: 'suc-forum.firebasestorage.app',
    iosBundleId: 'com.example.sucForum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8uolfyvhPLZz82SGmnPFtiNKSNSF6UII',
    appId: '1:837466394012:web:55b5d902253a2a3e068c59',
    messagingSenderId: '837466394012',
    projectId: 'suc-forum',
    authDomain: 'suc-forum.firebaseapp.com',
    storageBucket: 'suc-forum.firebasestorage.app',
  );
}
