import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/post.dart';
import '../models/comment.dart';
import '../services/firestore_service.dart';
import '../services/auth_service.dart';
import 'package:share_plus/share_plus.dart';
import '../widgets/post_detail/post_content.dart';
import '../widgets/post_detail/comment_list.dart';
import '../widgets/post_detail/comment_input.dart';

class PostDetailScreen extends StatefulWidget {
  final Post post;

  const PostDetailScreen({super.key, required this.post});

  @override
  State<PostDetailScreen> createState() => _PostDetailScreenState();
}

class _PostDetailScreenState extends State<PostDetailScreen> {
  bool _isLiked =
      false; // Simplification. Real app tracks likes subcollection per user.

  void _toggleLike() async {
    final firestoreService = context.read<FirestoreService>();
    final authService = context.read<AuthService>();
    final user = authService.user;

    if (user == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Please log in to like.')));
      return;
    }

    setState(() => _isLiked = !_isLiked);
    // Execute without awaiting so local cache processes instantly
    firestoreService.updateLike(widget.post.id, increment: _isLiked);
  }

  void _postComment(String text) async {
    if (text.isEmpty) return;

    final authService = context.read<AuthService>();
    final user = authService.user;
    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please log in to comment.')),
      );
      return;
    }

    final comment = Comment(
      id: '', // Generated by Firestore
      text: text,
      authorId: user.uid,
      authorName: user.isAnonymous
          ? "Anonymous User #${user.uid.substring(0, 5)}"
          : (user.displayName ?? "Unknown User"),
      authorRole: authService.isAdmin ? 'admin' : 'user',
      createdAt: DateTime.now(),
    );

    // Execute locally without blocking UI wait
    context.read<FirestoreService>().addComment(widget.post.id, comment);
  }

  void _reportPost() async {
    final reasonController = TextEditingController();
    final result = await showDialog<String>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Report Post'),
          content: TextField(
            controller: reasonController,
            decoration: const InputDecoration(
              hintText: 'Reason (e.g. 3R Violation)',
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel'),
            ),
            TextButton(
              onPressed: () => Navigator.pop(context, reasonController.text),
              child: const Text('Report'),
            ),
          ],
        );
      },
    );

    if (result != null && result.isNotEmpty) {
      if (!mounted) return;
      final user = context.read<AuthService>().user;
      final reporterId = user?.uid ?? 'anonymous_reporter';

      try {
        context.read<FirestoreService>().reportPost(
          widget.post.id,
          reporterId,
          result,
        );
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Post reported to admins.')),
          );
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error reporting post: $e')));
        }
      }
    }
  }

  void _sharePost() {
    Share.share(
      'Check out this post on SUC Forum!\n\n'
      '${widget.post.title}\n'
      'By: ${widget.post.authorName}\n\n'
      '${widget.post.text}',
      subject: widget.post.title,
    );
  }

  @override
  Widget build(BuildContext context) {
    final authService = context.watch<AuthService>();

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.post.topic),
        actions: [
          IconButton(
            icon: const Icon(Icons.share_outlined),
            onPressed: _sharePost,
            tooltip: 'Share Post',
          ),
          IconButton(
            icon: const Icon(Icons.report_problem),
            onPressed: authService.isAuthenticated ? _reportPost : null,
            tooltip: authService.isAuthenticated
                ? 'Report Post'
                : 'Log in to report',
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  PostContent(
                    post: widget.post,
                    isLiked: _isLiked,
                    onToggleLike: _toggleLike,
                  ),
                  const Divider(height: 32),
                  const Text(
                    'Comments',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 16),
                  CommentList(postId: widget.post.id),
                ],
              ),
            ),
          ),
          CommentInput(onSend: _postComment),
        ],
      ),
    );
  }
}
