import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/post.dart';
import '../models/comment.dart';
import '../services/firestore_service.dart';
import '../services/auth_service.dart';
import 'package:share_plus/share_plus.dart';
import '../utils/date_formatter.dart';

class PostDetailScreen extends StatefulWidget {
  final Post post;

  const PostDetailScreen({super.key, required this.post});

  @override
  State<PostDetailScreen> createState() => _PostDetailScreenState();
}

class _PostDetailScreenState extends State<PostDetailScreen> {
  final _commentController = TextEditingController();
  bool _isLiked =
      false; // Simplification. Real app tracks likes subcollection per user.

  void _toggleLike() async {
    final firestoreService = context.read<FirestoreService>();
    setState(() => _isLiked = !_isLiked);
    // Execute without awaiting so local cache processes instantly
    firestoreService.updateLike(widget.post.id, increment: _isLiked);
  }

  void _postComment() async {
    final text = _commentController.text.trim();
    if (text.isEmpty) return;

    final authService = context.read<AuthService>();
    final user = authService.user;
    if (user == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please log in to comment.')),
      );
      return;
    }

    final comment = Comment(
      id: '', // Generated by Firestore
      text: text,
      authorId: user.uid,
      authorName: user.isAnonymous
          ? "Anonymous User #${user.uid.substring(0, 5)}"
          : (user.displayName ?? "Unknown User"),
      authorRole: authService.isAdmin ? 'admin' : 'user',
      createdAt: DateTime.now(),
    );

    // Execute locally without blocking UI wait
    context.read<FirestoreService>().addComment(widget.post.id, comment);
    _commentController.clear();
  }

  void _reportPost() async {
    final reasonController = TextEditingController();
    final result = await showDialog<String>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Report Post'),
          content: TextField(
            controller: reasonController,
            decoration: const InputDecoration(
              hintText: 'Reason (e.g. 3R Violation)',
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel'),
            ),
            TextButton(
              onPressed: () => Navigator.pop(context, reasonController.text),
              child: const Text('Report'),
            ),
          ],
        );
      },
    );

    if (result != null && result.isNotEmpty) {
      if (!mounted) return;
      final user = context.read<AuthService>().user;
      final reporterId = user?.uid ?? 'anonymous_reporter';

      try {
        context.read<FirestoreService>().reportPost(
          widget.post.id,
          reporterId,
          result,
        );
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Post reported to admins.')),
          );
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error reporting post: $e')));
        }
      }
    }
  }

  void _sharePost() {
    Share.share(
      'Check out this post on SUC Forum!\n\n'
      '${widget.post.title}\n'
      'By: ${widget.post.authorName}\n\n'
      '${widget.post.text}',
      subject: widget.post.title,
    );
  }

  @override
  Widget build(BuildContext context) {
    final authService = context.watch<AuthService>();
    final firestoreService = context.read<FirestoreService>();

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.post.topic),
        actions: [
          IconButton(
            icon: const Icon(Icons.share_outlined),
            onPressed: _sharePost,
            tooltip: 'Share Post',
          ),
          IconButton(
            icon: const Icon(Icons.report_problem),
            onPressed: authService.isAuthenticated ? _reportPost : null,
            tooltip: authService.isAuthenticated
                ? 'Report Post'
                : 'Log in to report',
          ),
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    widget.post.title,
                    style: Theme.of(context).textTheme.headlineSmall,
                  ),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      const Icon(Icons.person, size: 16),
                      const SizedBox(width: 4),
                      Text(widget.post.authorName),
                      const Spacer(),
                      Text(DateFormatter.formatFull(widget.post.createdAt)),
                    ],
                  ),
                  const Divider(height: 32),
                  if (widget.post.imageUrl != null) ...[
                    widget.post.imageUrl!.startsWith('http')
                        ? Image.network(widget.post.imageUrl!)
                        : Image.memory(base64Decode(widget.post.imageUrl!)),
                    const SizedBox(height: 16),
                  ],
                  Text(widget.post.text, style: const TextStyle(fontSize: 16)),
                  const SizedBox(height: 24),
                  Row(
                    children: [
                      IconButton(
                        icon: Icon(
                          _isLiked
                              ? Icons.thumb_up
                              : Icons.thumb_up_alt_outlined,
                        ),
                        color: _isLiked ? Colors.blue : null,
                        onPressed: _toggleLike,
                      ),
                      Text(
                        '${widget.post.likesCount + (_isLiked ? 1 : 0)} Likes',
                      ),
                    ],
                  ),
                  const Divider(height: 32),
                  const Text(
                    'Comments',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 16),
                  StreamBuilder<List<Comment>>(
                    stream: firestoreService.getComments(widget.post.id),
                    builder: (context, snapshot) {
                      if (!snapshot.hasData) {
                        return const CircularProgressIndicator();
                      }
                      final comments = snapshot.data!;
                      if (comments.isEmpty) {
                        return const Text('No comments yet.');
                      }
                      return ListView.builder(
                        shrinkWrap: true,
                        physics: const NeverScrollableScrollPhysics(),
                        itemCount: comments.length,
                        itemBuilder: (context, index) {
                          final c = comments[index];
                          final bool isAdminComment = c.authorRole == 'admin';

                          return ListTile(
                            contentPadding: EdgeInsets.zero,
                            leading: CircleAvatar(
                              backgroundColor: isAdminComment
                                  ? Colors.blue[50]
                                  : Colors.grey[100],
                              child: Icon(
                                isAdminComment
                                    ? Icons.admin_panel_settings
                                    : Icons.person,
                                size: 20,
                              ),
                              // child: Icon(Icons.person, size: 20),
                            ),
                            title: Text(
                              c.authorName,
                              style: const TextStyle(
                                fontWeight: FontWeight.bold,
                                fontSize: 13,
                              ),
                            ),
                            subtitle: Text(c.text),
                          );
                        },
                      );
                    },
                  ),
                ],
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _commentController,
                    decoration: const InputDecoration(
                      hintText: 'Add a comment...',
                      border: OutlineInputBorder(),
                    ),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.send),
                  onPressed: _postComment,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
